/**
 * DO NOT EDIT THIS FILE
 * aside from changing the image path if you want
 */
import type { ErrorResult, NewsDetail, NewsInfo } from '@/types/news';

const DUMMY_TEXT =
	'<p>Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>';
const DUMMY_EXCERPT =
	'Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.';

const DATA_LIST: NewsDetail[] = [
	{
		id: 'a1b0e68b-24f4-447a-8097-0165db6caf53',
		title: 'Lorem ipsum dolor sit amet (A)',
		date: '2023-10-01T12:30:00.000Z',
		image: '/static/1.png',
		content: DUMMY_TEXT,
	},
	{
		id: 'b1b0e68b-24f4-447a-8097-0165db6caf53',
		title: 'Lorem ipsum dolor sit amet',
		date: '2023-10-01T11:30:00.000Z',
		image: '/static/1.png',
		content: DUMMY_TEXT,
	},
	{
		id: 'c1b0e68b-24f4-447a-8097-0165db6caf53',
		title: 'Lorem ipsum dolor sit amet',
		date: '2023-09-20T12:30:00.000Z',
		image: '/static/1.png',
		content: DUMMY_TEXT,
	},
	{
		id: 'd1b0e68b-24f4-447a-8097-0165db6caf53',
		title: 'Lorem ipsum dolor sit amet',
		date: '2023-09-12T12:45:00.000Z',
		image: '/static/1.png',
		content: DUMMY_TEXT,
	},
	{
		id: 'e1b0e68b-24f4-447a-8097-0165db6caf53',
		title: 'Lorem ipsum dolor sit amet',
		date: '2023-09-10T08:30:00.000Z',
		image: '/static/1.png',
		content: DUMMY_TEXT,
	},
	{
		id: 'f1b0e68b-24f4-447a-8097-0165db6caf53',
		title: 'Lorem ipsum dolor sit amet',
		date: '2023-09-01T12:30:00.000Z',
		image: '/static/1.png',
		content: DUMMY_TEXT,
	},
	{
		id: 'aab0e68b-24f4-447a-8097-0165db6caf53',
		title: 'Lorem ipsum dolor sit amet (Z)',
		date: '2023-09-01T12:30:00.000Z',
		image: '/static/1.png',
		content: DUMMY_TEXT,
	},
];

function mapDetailToInfo(list: NewsDetail[]): NewsInfo[] {
	return list.map((list) => {
		return {
			...list,
			excerpt: DUMMY_EXCERPT,
		} satisfies NewsInfo;
	});
}

export class NewsClient {
	public fetchList(): Promise<NewsInfo[]> {
		return Promise.resolve(mapDetailToInfo(DATA_LIST));
	}

	public fetchDetail(id: string): Promise<NewsDetail> {
		const data = DATA_LIST.find((item) => item.id === id);
		if (!data) {
			return Promise.reject({
				code: 404,
				message: 'Item not found',
			} satisfies ErrorResult);
		}

		return Promise.resolve(data);
	}
}
