/**
 * DO NOT EDIT THIS FILE
 */
export interface NewsDetail {
	id: string;
	title: string;
	date: string;
	image: string | null;
	content: string;
}

// The info interface is a subset of the complete detail
export type NewsInfo = Pick<NewsDetail, 'id' | 'title' | 'date' | 'image'> & {
	excerpt: string;
};

export interface ErrorResult {
	code: number;
	message: string;
}
